### ISSUE TITLE
acdc_preprocess.py and image/label names.

### ISSUE THREAD

**Issue by alqurri77** [cherise215/MaxStyle#2]
Hi;

acdc_preprocess.py expect the image and label name to be in the format:

```
mage_path_format = "/vol/medic02/users/cc215/data/ACDC/dataset/all/patient{}/image_" + frame + ".nii.gz"
label_path_format = "/vol/medic02/users/cc215/data/ACDC/dataset/all/patient{}/label_" + frame + ".nii.gz"
```

But the image & label name:

```
Info.cfg
patient001_frame01_gt.nii.gz  
patient001_frame12_gt.nii.gz
patient001_4d.nii.gz
patient001_frame01.nii.gz
patient001_frame12.nii.gz
```

How do I map between the two:

**Comment by cherise215** [comment]
please read our readme on how to reorganize the data.  In a nutshell, please rename and save the data as as patient{patient_id}/image_{frame}.nii.gz;patient{patient_id}/label_{frame}.nii.gz. For your case, "patient001_frame01.nii.gz"->"patient001/image_ED.nii.gz" ; "patient001_frame01_gt.nii.gz"->"patient001/label_ED.nii.gz"."patient001_frame12.nii.gz"->"patient001/image_ES.nii.gz" ; "patient001_frame12_gt.nii.gz"->"patient001/label_ES.nii.gz". You can have a look at Info.cfg to check which frame number corresponding to the ED/ES.
