### ISSUE TITLE
为什么要先Standard training再MaxStyle training

### ISSUE THREAD

**Issue by wangmingaaaaa** [cherise215/MaxStyle#4]
您好，为什么要先Standard training再MaxStyle training呢，是要训练图像解码器让它重建的图片好吗？

**Comment by cherise215** [comment]
joint training. No need for pretraining.

**Comment by wangmingaaaaa** [comment]
Can you elaborate on this? What you call joint training？
Why is the style map I generated visually a bunch of noise?

**Comment by wangmingaaaaa** [comment]
What should we do if the images generated by the reconstructed decoder are not good enough without pre-training?

**Comment by wangmingaaaaa** [comment]
I only need to run MaxStyle training and not Standard training, right?

**Comment by wangmingaaaaa** [comment]
May I ask what is the code for the style image generated during the visualization? Can you share it? Approximately how many epochs of training is the visualized image good?
